// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cnwavlbgmheachdevkhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNud2F2bGJnbWhlYWNoZGV2a2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NzIzODMsImV4cCI6MjA4MDM0ODM4M30.KALS2GiOSLEV46qn2g4gHNmThmLJqexBE6eilHxGWzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);